name: MOT ML Test Workflow

on:
  workflow_dispatch: {}

jobs:
  test-ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from MOT ML workflow (Autodun MOT Predictor)"
